### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by ketan582** [bricaud/gremlin-server-3.2.5-REST#2]
I get this while trying to build docker image. 

```
--2018-03-13 06:37:48--  http://apache.mirrors.ovh.net/ftp.apache.org/dist/tinkerpop/3.2.5/apache-tinkerpop-gremlin-server-3.2.5-bin.zip
Resolving apache.mirrors.ovh.net... 213.32.5.7, 2001:41d0:202:100:213:32:5:7
Connecting to apache.mirrors.ovh.net|213.32.5.7|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-13 06:37:53 ERROR 404: Not Found.
```

**Comment by bricaud** [comment]
Open the Dockerfile and change (on line 10) the address for downloading the file to this one:
https://archive.apache.org/dist/tinkerpop/3.2.5/apache-tinkerpop-gremlin-server-3.2.5-bin.zip

**Comment by bricaud** [comment]
I have modified the code and changed the address.
Thanks for your feedback
